name: vinniefm.com
url: http://vinniefm.com
description: Project documentation and Portfolio by Vince Mease

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
